#!/usr/bin/env python3

import argparse

def print_version():
	print("0.1")
	
def print_usage():
	print("git myPlugin [add-since|add-author]")
	
def start_smart_work(since=True, author=True):
	print("Starting smart work...")
	print("Done")
	
	
def main():
	print("ran plugin wrapper!")
	
	parser = argparse.ArgumentParser()
	parser.add_argument("-v", "--version", help="Display the version of this plugin", action='store_true')
	parser.add_argument("--since", help="Add the @since annotations to project", action='store_true')
	parser.add_argument("--author", help="Add the @author annotations to project", action='store_true')
	
	args = parser.parse_args()
	
	if args.version:
		print_version()
		return
	
	add_since  = True if args.since else False
	add_author = True if args.author else False
	start_smart_work(add_since, add_author)
	

if __name__ == "__main__":
	main()

